- name: mkdir for postgres
  file:
    path: "{{ postgres_root }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy patroni-init-walg.yml.j2
  template:
    src: patroni-init-walg.yml.j2
    dest: "{{ postgres_root }}/patroni.yml"

- name: Deploy afefelov/patroni-class-pg-9.6-walg
  docker_container:
    name: "{{ patroni_node_name }}"
    image: "afefelov/patroni-class-pg-9.6-walg"
    detach: true
    state: started
    restart: yes
    pull: yes
    env:
      TERM: 'xterm'
      TZ: Europe/Moscow
      AWS_ACCESS_KEY_ID: "=)"
      AWS_SECRET_ACCESS_KEY: "=)"
      PGPORT: 5432
      WALE_S3_PREFIX: "s3://pgconf-patroni-class/backup"
    dns_servers:
      - "{{ ansible_host }}"
    expose:
      - 5432
      - 8008
    network_mode: host
    ports:
        - "5432:5432"
        - "8008:8008"
    volumes:
        - "{{ postgres_root }}:/var/lib/postgresql"

- name: fix /var/lib/postgresql permission
  command: "docker exec {{ patroni_node_name }} chown -R postgres:postgres /var/lib/postgresql"
  when: patroni_node_name is defined

- name: fix /var/log/postgresql permission
  command: "docker exec {{ patroni_node_name }} chown postgres:postgres /var/log/postgresql"
  when: patroni_node_name is defined
